spring:
  main:
    web-application-type: none

runner:
  service:
    base-url: https://localhost:8443/api/v1
    skip-ssl-verify: true
  jwt:
    token-uri: http://localhost:8080/realms/encryption/protocol/openid-connect/token
    client-id: encryption-runner
    client-secret: changeit
    grant-type: client_credentials
  load:
    file-size-kb: 900
    concurrency: 10
    iterations: 100
    warmup: 10

logging:
  file:
    name: load.log
