cli.service-url=https://127.0.0.1:8443
cli.jwt.token-uri=https://localhost:8080/realms/encryption/protocol/openid-connect/token
cli.jwt.client-id=test-consumer
cli.jwt.client-secret=test-consumer-secret
cli.suffix-to-encrypt=.csv,.txt,.json,.xml
cli.log-dir=./logs
